"""initial migration, added a new column 'date_added' to the models

Revision ID: 95ca38fe6c9d
Revises:
Create Date: 2020-12-27 08:42:13.862157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ca38fe6c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailymail_columns', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.create_index('ix_dailymail_columns_link', 'dailymail_columns', ['link'], unique=1)
    # op.drop_index('ix_dailymail_columns_link', table_name='dailymail_columns')
    op.create_unique_constraint(None, 'dailymail_columns', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dailymail_columns', type_='unique')
    # op.create_index('ix_dailymail_columns_link', 'dailymail_columns', ['link'], unique=1)
    op.drop_column('dailymail_columns', 'date_added')
    # ### end Alembic commands ###
